import type { ModelInfo } from "../model.js"

export const fireworksModels = {
	"accounts/fireworks/models/kimi-k2p6": {
		maxTokens: 32_768,
		contextWindow: 262_144,
		supportsImages: true,
		supportsPromptCache: true,
		supportsReasoningBinary: true,
		preserveReasoning: true,
		inputPrice: 0.95,
		outputPrice: 4,
		cacheReadsPrice: 0.16,
		description:
			"Kimi K2.6 is Moonshot AI's current flagship agentic model on Fireworks, with 262K context, vision input, tool use, prompt caching, and controllable thinking modes.",
	},
	"accounts/fireworks/models/kimi-k2p5": {
		maxTokens: 32_768,
		contextWindow: 262_144,
		supportsImages: true,
		supportsPromptCache: true,
		supportsReasoningBinary: true,
		preserveReasoning: true,
		inputPrice: 0.6,
		outputPrice: 3,
		cacheReadsPrice: 0.1,
		description:
			"Kimi K2.5 is Moonshot AI's flagship agentic multimodal model on Fireworks, combining vision and text with thinking and non-thinking modes for coding and agent workflows.",
	},
	"accounts/fireworks/models/deepseek-v4-pro": {
		maxTokens: 384_000,
		contextWindow: 1_000_000,
		supportsImages: false,
		supportsPromptCache: true,
		preserveReasoning: true,
		inputPrice: 1.74,
		outputPrice: 3.48,
		cacheReadsPrice: 0.145,
		description:
			"DeepSeek V4 Pro is Fireworks' flagship DeepSeek V4 model with long-context reasoning, strong coding, tool use, JSON output, and prompt caching support.",
	},
	"accounts/fireworks/models/deepseek-v4-flash": {
		maxTokens: 384_000,
		contextWindow: 1_000_000,
		supportsImages: false,
		supportsPromptCache: true,
		preserveReasoning: true,
		inputPrice: 0.14,
		outputPrice: 0.28,
		cacheReadsPrice: 0.028,
		description:
			"DeepSeek V4 Flash is a lower-cost DeepSeek V4 variant on Fireworks for fast long-context coding, reasoning, and agentic workflows.",
	},
	"accounts/fireworks/models/glm-5p1": {
		maxTokens: 131_072,
		contextWindow: 202_752,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 1.4,
		outputPrice: 4.4,
		cacheReadsPrice: 0.26,
		description:
			"Z.ai GLM-5.1 on Fireworks is a frontier coding and agentic reasoning model with a 202K context window and prompt caching.",
	},
	"accounts/fireworks/models/qwen3p6-plus": {
		maxTokens: 32_768,
		contextWindow: 262_144,
		supportsImages: true,
		supportsPromptCache: true,
		inputPrice: 0.5,
		outputPrice: 3,
		cacheReadsPrice: 0.1,
		description:
			"Qwen 3.6 Plus on Fireworks is a current Qwen model for agentic reasoning and coding, with vision input and tool-use support.",
	},
	"accounts/fireworks/models/minimax-m2p7": {
		maxTokens: 196_608,
		contextWindow: 196_608,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.3,
		outputPrice: 1.2,
		cacheReadsPrice: 0.06,
		description:
			"MiniMax M2.7 on Fireworks is a current long-context text model optimized for agentic coding and general-purpose workflows.",
	},
	"accounts/fireworks/models/minimax-m2p5": {
		maxTokens: 196_608,
		contextWindow: 196_608,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.3,
		outputPrice: 1.2,
		cacheReadsPrice: 0.03,
		description:
			"MiniMax M2.5 on Fireworks is a long-context text model for coding, tool use, and agent workflows.",
	},
	"accounts/fireworks/models/gpt-oss-120b": {
		maxTokens: 131_072,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.15,
		outputPrice: 0.6,
		cacheReadsPrice: 0.015,
		description:
			"OpenAI gpt-oss-120b on Fireworks is a production-grade open-weight model with strong reasoning, function calling, tool use, and structured-output support.",
	},
	"accounts/fireworks/models/gpt-oss-20b": {
		maxTokens: 131_072,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.07,
		outputPrice: 0.3,
		cacheReadsPrice: 0.035,
		description:
			"OpenAI gpt-oss-20b on Fireworks is a compact open-weight model for lower-latency, lower-cost text and reasoning workloads.",
	},
	"accounts/fireworks/models/kimi-k2-instruct-0905": {
		maxTokens: 16_384,
		contextWindow: 262_144,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.6,
		outputPrice: 2.5,
		cacheReadsPrice: 0.15,
		deprecated: true,
		description:
			"Deprecated Kimi K2 September 2025 checkpoint retained for existing configurations. Use accounts/fireworks/models/kimi-k2p6 for new configurations.",
	},
	"accounts/fireworks/models/kimi-k2-instruct": {
		maxTokens: 16_384,
		contextWindow: 128_000,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0.6,
		outputPrice: 2.5,
		deprecated: true,
		description:
			"Deprecated Kimi K2 instruct checkpoint retained for existing configurations. Use accounts/fireworks/models/kimi-k2p6 for new configurations.",
	},
	"accounts/fireworks/models/kimi-k2-thinking": {
		maxTokens: 16_000,
		contextWindow: 256_000,
		supportsImages: false,
		supportsPromptCache: true,
		supportsTemperature: true,
		preserveReasoning: true,
		defaultTemperature: 1,
		inputPrice: 0.6,
		outputPrice: 2.5,
		cacheReadsPrice: 0.15,
		deprecated: true,
		description:
			"Deprecated Kimi K2 Thinking checkpoint retained for existing configurations. Use accounts/fireworks/models/kimi-k2p6 or accounts/fireworks/models/kimi-k2p5 for current Kimi thinking support.",
	},
	"accounts/fireworks/models/minimax-m2": {
		maxTokens: 4_096,
		contextWindow: 204_800,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0.3,
		outputPrice: 1.2,
		deprecated: true,
		description:
			"Deprecated MiniMax M2 checkpoint retained for existing configurations. Use accounts/fireworks/models/minimax-m2p7 for new configurations.",
	},
	"accounts/fireworks/models/minimax-m2p1": {
		maxTokens: 4_096,
		contextWindow: 204_800,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0.3,
		outputPrice: 1.2,
		deprecated: true,
		description:
			"Deprecated MiniMax M2.1 checkpoint retained for existing configurations. Use accounts/fireworks/models/minimax-m2p7 for new configurations.",
	},
	"accounts/fireworks/models/qwen3-235b-a22b-instruct-2507": {
		maxTokens: 32_768,
		contextWindow: 256_000,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0.22,
		outputPrice: 0.88,
		deprecated: true,
		description:
			"Deprecated Qwen3 235B July 2025 checkpoint retained for existing configurations. Use accounts/fireworks/models/qwen3p6-plus for current Qwen support.",
	},
	"accounts/fireworks/models/qwen3-coder-480b-a35b-instruct": {
		maxTokens: 32_768,
		contextWindow: 256_000,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0.45,
		outputPrice: 1.8,
		deprecated: true,
		description:
			"Deprecated Qwen3 Coder checkpoint retained for existing configurations. Use accounts/fireworks/models/qwen3p6-plus for current Qwen support.",
	},
	"accounts/fireworks/models/deepseek-r1-0528": {
		maxTokens: 20_480,
		contextWindow: 160_000,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 3,
		outputPrice: 8,
		deprecated: true,
		description:
			"Deprecated DeepSeek R1 May 2025 checkpoint retained for existing configurations. Use accounts/fireworks/models/deepseek-v4-pro for current DeepSeek support.",
	},
	"accounts/fireworks/models/deepseek-v3": {
		maxTokens: 16_384,
		contextWindow: 128_000,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0.9,
		outputPrice: 0.9,
		deprecated: true,
		description:
			"Deprecated DeepSeek V3 checkpoint retained for existing configurations. Use accounts/fireworks/models/deepseek-v4-pro for current DeepSeek support.",
	},
	"accounts/fireworks/models/deepseek-v3p1": {
		maxTokens: 16_384,
		contextWindow: 163_840,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0.56,
		outputPrice: 1.68,
		deprecated: true,
		description:
			"Deprecated DeepSeek V3.1 checkpoint retained for existing configurations. Use accounts/fireworks/models/deepseek-v4-pro for current DeepSeek support.",
	},
	"accounts/fireworks/models/deepseek-v3p2": {
		maxTokens: 16_384,
		contextWindow: 163_840,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0.56,
		outputPrice: 1.68,
		deprecated: true,
		description:
			"Deprecated DeepSeek V3.2 checkpoint retained for existing configurations. Use accounts/fireworks/models/deepseek-v4-pro for current DeepSeek support.",
	},
	"accounts/fireworks/models/glm-4p5": {
		maxTokens: 16_384,
		contextWindow: 128_000,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0.55,
		outputPrice: 2.19,
		deprecated: true,
		description:
			"Deprecated Z.ai GLM-4.5 checkpoint retained for existing configurations. Use accounts/fireworks/models/glm-5p1 for current GLM support.",
	},
	"accounts/fireworks/models/glm-4p5-air": {
		maxTokens: 16_384,
		contextWindow: 128_000,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0.55,
		outputPrice: 2.19,
		deprecated: true,
		description:
			"Deprecated Z.ai GLM-4.5-Air checkpoint retained for existing configurations. Use accounts/fireworks/models/glm-5p1 for current GLM support.",
	},
	"accounts/fireworks/models/glm-4p6": {
		maxTokens: 25_344,
		contextWindow: 198_000,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0.55,
		outputPrice: 2.19,
		deprecated: true,
		description:
			"Deprecated Z.ai GLM-4.6 checkpoint retained for existing configurations. Use accounts/fireworks/models/glm-5p1 for current GLM support.",
	},
	"accounts/fireworks/models/glm-4p7": {
		maxTokens: 25_344,
		contextWindow: 198_000,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0.55,
		outputPrice: 2.19,
		deprecated: true,
		description:
			"Deprecated Z.ai GLM-4.7 checkpoint retained for existing configurations. Use accounts/fireworks/models/glm-5p1 for current GLM support.",
	},
	"accounts/fireworks/models/llama-v3p3-70b-instruct": {
		maxTokens: 16_384,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0.9,
		outputPrice: 0.9,
		deprecated: true,
		description: "Deprecated Meta Llama 3.3 70B Instruct checkpoint retained for existing configurations.",
	},
	"accounts/fireworks/models/llama4-maverick-instruct-basic": {
		maxTokens: 16_384,
		contextWindow: 131_072,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0.22,
		outputPrice: 0.88,
		deprecated: true,
		description: "Deprecated Llama 4 Maverick checkpoint retained for existing configurations.",
	},
	"accounts/fireworks/models/llama4-scout-instruct-basic": {
		maxTokens: 16_384,
		contextWindow: 131_072,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0.15,
		outputPrice: 0.6,
		deprecated: true,
		description: "Deprecated Llama 4 Scout checkpoint retained for existing configurations.",
	},
} as const satisfies Record<string, ModelInfo>

export type FireworksModelId = keyof typeof fireworksModels

export const fireworksDefaultModelId: FireworksModelId = "accounts/fireworks/models/kimi-k2p6"
