import type { ModelInfo } from "../model.js"

// https://docs.mistral.ai/models/overview
// https://docs.mistral.ai/getting-started/models/models_overview/
export type MistralModelId = keyof typeof mistralModels

export const mistralDefaultModelId: MistralModelId = "codestral-latest"

export const mistralModels = {
	"mistral-medium-latest": {
		maxTokens: 8192,
		contextWindow: 256_000,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 1.5,
		outputPrice: 7.5,
		description: "Mistral Medium 3.5 is Mistral's frontier general-purpose multimodal model.",
	},
	"mistral-medium-3-5": {
		maxTokens: 8192,
		contextWindow: 256_000,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 1.5,
		outputPrice: 7.5,
		description: "Mistral Medium 3.5 is Mistral's frontier general-purpose multimodal model.",
	},
	"mistral-medium-3-5+1": {
		maxTokens: 8192,
		contextWindow: 256_000,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 1.5,
		outputPrice: 7.5,
		description: "Mistral Medium 3.5 is Mistral's frontier general-purpose multimodal model.",
	},
	"mistral-small-latest": {
		maxTokens: 8192,
		contextWindow: 256_000,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0.15,
		outputPrice: 0.6,
		description: "Mistral Small 4 is Mistral's latest small, fast, cost-effective multimodal model.",
	},
	"mistral-small-2603": {
		maxTokens: 8192,
		contextWindow: 256_000,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0.15,
		outputPrice: 0.6,
		description: "Mistral Small 4 is Mistral's latest small, fast, cost-effective multimodal model.",
	},
	"mistral-large-latest": {
		maxTokens: 8192,
		contextWindow: 256_000,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0.5,
		outputPrice: 1.5,
		description: "Mistral Large 3 is Mistral's large-scale multimodal model.",
	},
	"mistral-large-2512": {
		maxTokens: 8192,
		contextWindow: 256_000,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0.5,
		outputPrice: 1.5,
		description: "Mistral Large 3 is Mistral's large-scale multimodal model.",
	},
	"mistral-large-2512+1": {
		maxTokens: 8192,
		contextWindow: 256_000,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0.5,
		outputPrice: 1.5,
		description: "Mistral Large 3 is Mistral's large-scale multimodal model.",
	},
	"codestral-latest": {
		maxTokens: 8192,
		contextWindow: 128_000,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0.3,
		outputPrice: 0.9,
		description: "Codestral v25.08 is Mistral's code-generation model.",
	},
	"codestral-2508": {
		maxTokens: 8192,
		contextWindow: 128_000,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0.3,
		outputPrice: 0.9,
		description: "Codestral v25.08 is Mistral's code-generation model.",
	},
	"codestral-2508+1": {
		maxTokens: 8192,
		contextWindow: 128_000,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0.3,
		outputPrice: 0.9,
		description: "Codestral v25.08 is Mistral's code-generation model.",
	},
	"devstral-medium-latest": {
		maxTokens: 8192,
		contextWindow: 256_000,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0.4,
		outputPrice: 2.0,
		description: "Devstral 2 is Mistral's agentic coding model.",
	},
	"devstral-2512": {
		maxTokens: 8192,
		contextWindow: 256_000,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0.4,
		outputPrice: 2.0,
		description: "Devstral 2 is Mistral's agentic coding model.",
	},
	"devstral-2512+2": {
		maxTokens: 8192,
		contextWindow: 256_000,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0.4,
		outputPrice: 2.0,
		description: "Devstral 2 is Mistral's agentic coding model.",
	},
	"magistral-medium-latest": {
		maxTokens: 8192,
		contextWindow: 128_000,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 2.0,
		outputPrice: 5.0,
		description: "Magistral Medium 1.2 is Mistral's reasoning-focused multimodal model.",
	},
	"magistral-medium-2509": {
		maxTokens: 8192,
		contextWindow: 128_000,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 2.0,
		outputPrice: 5.0,
		description: "Magistral Medium 1.2 is Mistral's reasoning-focused multimodal model.",
	},
	"magistral-medium-2509+1": {
		maxTokens: 8192,
		contextWindow: 128_000,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 2.0,
		outputPrice: 5.0,
		description: "Magistral Medium 1.2 is Mistral's reasoning-focused multimodal model.",
	},
	"ministral-14b-latest": {
		maxTokens: 8192,
		contextWindow: 256_000,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0.2,
		outputPrice: 0.2,
		description: "Ministral 3 14B is Mistral's efficient edge-friendly multimodal model.",
	},
	"ministral-14b-2512+1": {
		maxTokens: 8192,
		contextWindow: 256_000,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0.2,
		outputPrice: 0.2,
		description: "Ministral 3 14B is Mistral's efficient edge-friendly multimodal model.",
	},
	"ministral-8b-latest": {
		maxTokens: 8192,
		contextWindow: 256_000,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0.15,
		outputPrice: 0.15,
		description: "Ministral 3 8B is Mistral's efficient edge-friendly multimodal model.",
	},
	"ministral-8b-2512+1": {
		maxTokens: 8192,
		contextWindow: 256_000,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0.15,
		outputPrice: 0.15,
		description: "Ministral 3 8B is Mistral's efficient edge-friendly multimodal model.",
	},
	"ministral-3b-latest": {
		maxTokens: 8192,
		contextWindow: 256_000,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0.1,
		outputPrice: 0.1,
		description: "Ministral 3 3B is Mistral's efficient edge-friendly multimodal model.",
	},
	"ministral-3b-2512+1": {
		maxTokens: 8192,
		contextWindow: 256_000,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0.1,
		outputPrice: 0.1,
		description: "Ministral 3 3B is Mistral's efficient edge-friendly multimodal model.",
	},
	"mistral-small-2506": {
		maxTokens: 8192,
		contextWindow: 32_000,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0.2,
		outputPrice: 0.6,
		deprecated: true,
		description: "Deprecated Mistral Small model retained for existing configurations; use mistral-small-latest.",
	},
	"pixtral-large-latest": {
		maxTokens: 8192,
		contextWindow: 128_000,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 2.0,
		outputPrice: 6.0,
		deprecated: true,
		description: "Deprecated Pixtral Large alias retained for existing configurations; use mistral-large-latest.",
	},
} as const satisfies Record<string, ModelInfo>

export const MISTRAL_DEFAULT_TEMPERATURE = 1
