import type { ModelInfo } from "../model.js"

// https://api.sambanova.ai/v1/models
export const sambaNovaModels = {
	"Meta-Llama-3.3-70B-Instruct": {
		maxTokens: 3_072,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0.6,
		outputPrice: 1.2,
		description: "Meta Llama 3.3 70B Instruct on SambaNova with 128K context.",
	},
	"DeepSeek-V3.1": {
		maxTokens: 7_168,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 3,
		outputPrice: 4.5,
		description: "DeepSeek V3.1 on SambaNova with 128K context.",
	},
	"DeepSeek-V3.2": {
		maxTokens: 7_168,
		contextWindow: 32_768,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 3,
		outputPrice: 4.5,
		description: "DeepSeek V3.2 on SambaNova with 32K context.",
	},
	"Llama-4-Maverick-17B-128E-Instruct": {
		maxTokens: 4_096,
		contextWindow: 131_072,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0.63,
		outputPrice: 1.8,
		description: "Meta Llama 4 Maverick 17B 128E Instruct on SambaNova with 128K context.",
	},
	"MiniMax-M2.7": {
		maxTokens: 196_608,
		contextWindow: 196_608,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0.6,
		outputPrice: 2.4,
		description: "MiniMax M2.7 on SambaNova with 196K context.",
	},
	"gemma-3-12b-it": {
		maxTokens: 131_072,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0.35,
		outputPrice: 0.59,
		description: "Gemma 3 12B IT on SambaNova with 128K context.",
	},
	"gemma-4-31B-it": {
		maxTokens: 131_072,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0.38,
		outputPrice: 1.15,
		description: "Gemma 4 31B IT on SambaNova with 128K context.",
	},
	"gpt-oss-120b": {
		maxTokens: 131_072,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0.22,
		outputPrice: 0.59,
		description: "OpenAI gpt-oss-120b on SambaNova with 128K context.",
	},
	"Meta-Llama-3.1-8B-Instruct": {
		maxTokens: 8_192,
		contextWindow: 16_384,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0.1,
		outputPrice: 0.2,
		deprecated: true,
		description: "Deprecated Meta Llama 3.1 8B Instruct SambaNova entry retained for existing configurations.",
	},
	"DeepSeek-R1": {
		maxTokens: 8_192,
		contextWindow: 32_768,
		supportsImages: false,
		supportsPromptCache: false,
		supportsReasoningBudget: true,
		inputPrice: 5,
		outputPrice: 7,
		deprecated: true,
		description: "Deprecated DeepSeek R1 SambaNova entry retained for existing configurations.",
	},
	"DeepSeek-V3-0324": {
		maxTokens: 8_192,
		contextWindow: 32_768,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 3,
		outputPrice: 4.5,
		deprecated: true,
		description: "Deprecated DeepSeek V3 0324 SambaNova entry retained for existing configurations.",
	},
	"Qwen3-32B": {
		maxTokens: 8_192,
		contextWindow: 8_192,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0.4,
		outputPrice: 0.8,
		deprecated: true,
		description: "Deprecated Qwen3 32B SambaNova entry retained for existing configurations.",
	},
} as const satisfies Record<string, ModelInfo>

export type SambaNovaModelId = keyof typeof sambaNovaModels

export const sambaNovaDefaultModelId: SambaNovaModelId = "Meta-Llama-3.3-70B-Instruct"
