import {
	DEFAULT_MEMORY_MAX_CHARACTERS,
	DEFAULT_MEMORY_MAX_ENTRIES,
	DEFAULT_MEMORY_PENDING_CANDIDATE_LIMIT,
	MEMORY_CONTEXT_WINDOW_AUTO_THRESHOLD,
} from "@roo-code/types"

export {
	DEFAULT_MEMORY_MAX_CHARACTERS,
	DEFAULT_MEMORY_MAX_ENTRIES,
	DEFAULT_MEMORY_PENDING_CANDIDATE_LIMIT,
	MEMORY_CONTEXT_WINDOW_AUTO_THRESHOLD,
}

export const MEMORY_STORE_VERSION = 1 as const
export const MEMORY_DIRECTORY_NAME = "memory"
export const GLOBAL_MEMORY_FILE_NAME = "global.json"
export const WORKSPACE_MEMORY_DIRECTORY_NAME = "workspaces"
export const MEMORY_PROMPT_HEADER = "<memory_context>"
export const MEMORY_PROMPT_FOOTER = "</memory_context>"
