export function getToolUseGuidelinesSection(): string {
	return `# Tool Use Guidelines

1. Assess what information you already have and what information you need to proceed with the task.
2. Choose the most appropriate tool based on the task and the tool descriptions provided. Assess if you need additional information to proceed, and which of the available tools would be most effective for gathering this information. For example using the list_files tool is more effective than running a command like \`ls\` in the terminal. It's critical that you think about each available tool and use the one that best fits the current step in the task.
3. If the user asks for an action that the current mode can perform with its available tools, do the work directly in the current mode instead of reflexively routing to Code or another mode. If the current mode cannot perform the action because the required tool or tool group is unavailable, do not refuse or tell the user to do it manually. Use switch_mode for a direct mode change or new_task for delegation so a capable mode can perform the work. Default routing: terminal/command work -> Code for implementation, Debug for troubleshooting, or CLI Tools for pure command-line work when available; file edits -> Code or an appropriate editing specialist; visual UI inspection -> a mode with visual_browser_inspector; image asset generation -> a mode with image_generation. For explicit image generation or image editing requests, use generate_image directly when available; otherwise route to an image-capable mode. Do not use visual_browser_inspector, Playwright/browser automation, MCP tools, or manual web UI workflows for image generation unless the user explicitly asks to operate or inspect a browser/web app. If the user does not provide an output path, choose a safe workspace-relative image asset path such as images/<descriptive-name>.png. Ask for clarification only when no sensible destination mode exists.
4. For creating or editing file contents, prefer the normal write/edit tools available to your mode over execute_command shell here-strings, heredocs, or echo chains. Use execute_command for running commands, tests, builds, package managers, scripts, or shell operations rather than embedding large file contents in command strings.
5. For repository or code searches, prefer dedicated search tools over shell text-search commands. On Windows/cmd.exe, avoid long findstr alternation patterns; use split searches or PowerShell Select-String when shell search is necessary, and treat findstr exit code 1 as no matches when there is no error output.
6. If multiple actions are needed and they are independent (such as unrelated reads, searches, audits, tests, or analysis), you may use multiple tools in a single message when appropriate so they can run in parallel where supported. Keep dependent steps sequential, and do not parallelize tool calls that may conflict, depend on each other, or modify the same files. Each tool use should be informed by the results of previous tool uses. Do not assume the outcome of any tool use.

By carefully considering the user's response after tool executions, you can react accordingly and make informed decisions about how to proceed with the task. This iterative process helps ensure the overall success and accuracy of your work.`
}
